variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_package

build_package:mac:
  stage: build_package
  tags:
    - mac
  only:
    - tags
  script:
    - cd src/
    - npm version $CI_COMMIT_TAG
    - npm pack .
    - tar xzvf com.unity.mathematics-$CI_COMMIT_TAG.tgz
    - cd ..
    - python Tools/CI/validation.py --package-path src/package
    - cd src/
    - echo "npm publish com.unity.mathematics-$CI_COMMIT_TAG.tgz"
